### ISSUE TITLE
Issue when posting through proxy

### ISSUE THREAD

**Issue by frankra** [frankrafael/grunt-middleware-proxy#7]
When POSTing data through a proxied endpoint, the request hangs and the following error is displayed:

```
Running "watch:default" (watch) task
Waiting...
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at /Users/Owner/GITRepo/MyProject-UI/node_modules/serve-index/index.js:104:11
    at call (/Users/Owner/GITRepo/MyProject-UI/node_modules/connect/index.js:239:7)
    at next (/Users/Owner/GITRepo/MyProject-UI/node_modules/connect/index.js:183:5)
    at serveStatic (/Users/Owner/GITRepo/MyProject-UI/node_modules/serve-static/index.js:74:16)
    at call (/Users/Owner/GITRepo/MyProject-UI/node_modules/connect/index.js:239:7)
    at next (/Users/Owner/GITRepo/MyProject-UI/node_modules/connect/index.js:183:5)
    at IncomingMessage.<anonymous> (/Users/Owner/GITRepo/MyProject-UI/node_modules/grunt-middleware-proxy/lib/Utils.js:252:11)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```

**Comment by leolarson3** [comment]
I have a similar issue, but I eventually get a 504 gateway error.

After I post, all subsequent action on that proxy gets the 504.

Has this been fixed?

**Comment by frankra** [comment]
@leolarson3 unfortunately not... I have a guessing though... Are you trying to proxy other content than json/plain text? Can you please provide more info about the service you are proxying? No need for url names or real parameters, just stuff like: 'Is an OData API, where I sent something like this: {data..} and expect like this {data..}'

Meanwhile I will try to look into this again during this week.

Thanks!

**Comment by leolarson3** [comment]
It was pretty basic JSON, nothing special going on.

POST Body:
{"item":{"reqAreaCode":"MINOR1",
          "id":"999999999",
          "minorField":"4",
          "status":"A",
          "acceptedDate":"2016-09-09",
          "acceptedTermCode":"2017FA",
          "completionDate":"2016-09-24",
          "completionTermCode":"2017FA",
          "advisorid":"888888888",
          "comment":"test minor1",
          "expectedGraduationTerm":"",
          "associatedCourseDept":"",
          "associatedCourseOption":"",
          "studentEmail":"",
          "advisorEmail":""}}

Response:  
{
  "summary": {
    "success": 1,
    "failures": 0
  }
}

**Comment by frankra** [comment]
@leolarson3 Man.. I spent some time looking into this issue and I could not find the root cause. The weird thing is that the request made in the `proxyThroughProxy` handle sometimes just won't come back... There is no error or anything, it just times out. I have a guessing that this might have been caused by a redirect or something, but I could not analyze it further.

I will try to find some time during the weekend to look into this, but it would be cool if you could help me from your side trying to troubleshoot the issue in your context, perhaps we have even different issues.

Thanks!

**Comment by chhaymenghong** [comment]
I have the same issue trying to do a multipart/form-data post. Anything new on this?
